# Generated by Django 6.0.3 on 2026-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='tag', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#8B5CF6', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='category',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='category',
            name='position',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
