# Generated by Django 6.0.3 on 2026-04-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_and_more'),
        ('folders', '0005_alter_folder_unique_together_alter_folder_color_and_more'),
        ('labels', '0002_alter_label_options_alter_label_unique_together_and_more'),
        ('tags', '0002_alter_tag_unique_together_alter_tag_name_and_more'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='label',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='todos', to='labels.label'),
        ),
        migrations.AddField(
            model_name='todo',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='folders.folder'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['folder'], name='todos_todo_folder__8005fa_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['category'], name='todos_todo_categor_ea39cb_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['status'], name='todos_todo_status_9f7c48_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['priority'], name='todos_todo_priorit_93f987_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['due_date'], name='todos_todo_due_dat_f2739d_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['folder', 'position'], name='todos_todo_folder__231b3d_idx'),
        ),
    ]
