# Generated by Django 6.0.3 on 2026-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='#6B7280', max_length=7),
        ),
        migrations.RemoveField(
            model_name='label',
            name='title',
        ),
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
    ]
