# Generated by Django 6.0.3 on 2026-04-01 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.CharField(default='#2563EB', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'name')},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
