# Generated by Django 6.0.3 on 2026-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_folder_user_alter_folder_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
        migrations.AlterField(
            model_name='folder',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
    ]
