# Generated by Django 6.0.3 on 2026-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_todos', '0001_initial'),
        ('todos', '0002_alter_todo_options_remove_todo_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtodo',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='subtodo',
            name='is_done',
        ),
        migrations.AddField(
            model_name='subtodo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtodo',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='subtodo',
            index=models.Index(fields=['todo'], name='sub_todos_s_todo_id_6ccf24_idx'),
        ),
        migrations.AddIndex(
            model_name='subtodo',
            index=models.Index(fields=['todo', 'position'], name='sub_todos_s_todo_id_2916c1_idx'),
        ),
    ]
